catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.box_list, name='box_list'),
    url(r'^get_pass/(?P<pk>\d+)/$', views.get_pass, name='get_pass'),
    url(r'^return_pass/(?P<pk>\d+)/$', views.return_pass, name='return_pass'),
    url(r'^search_form/$', views.search_form, name='search_form'),
    url(r'^search/$', views.search, name='search'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('catalog.urls')),
]

catalog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Arendator(models.Model):
    AUTO_MARK = (
        ('N', 'Nissan'),
        ('M', 'Mitsubisi'),
        ('L', 'Lada'),
    )

    person = models.CharField(blank=True,max_length=30, verbose_name='ФИО')
    gos_num = models.CharField(blank=True,max_length=9, verbose_name='Гос. номер')
    box_num = models.CharField(blank=True,max_length=3, unique=True, verbose_name='Номер бокса')
    auto = models.CharField(blank=True,max_length=1, choices=AUTO_MARK, verbose_name='Марка машины')
    has_pass = models.BooleanField(default=False, verbose_name='Пропуск получен')
    registered = models.DateField(blank=True,default=timezone.now, verbose_name='Дата начала аренды')
    ended = models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды')


    def get_pass(self):
        if self.has_pass == False:
            self.has_pass = True
        self.save()


    def return_pass(self):
        if self.has_pass == True:
            self.has_pass = False
        self.save()


    def __str__(self):
        return self.person

catalog/forms.py
from django import forms
from .models import Arendator

class ArendatorForm(forms.ModelForm):
    class Meta:
        model = Arendator
        fields = ['person', 'gos_num',
                  'box_num', 'auto',
                  'registered', 'ended']

catalog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, HttpResponse
from .models import Arendator
from .forms import ArendatorForm

def box_list(request):
    boxes = Arendator.objects.filter().order_by('box_num')
    return render(request, 'catalog/box_list.html', {'boxes': boxes})


def get_pass(request, pk):
    box = get_object_or_404(Arendator, pk=pk)
    box.get_pass()
    return render(request, 'catalog/get_pass.html', {'box': box})


def return_pass(request, pk):
    box = get_object_or_404(Arendator, pk=pk)
    box.return_pass()
    return render(request, 'catalog/return_pass.html', {'box': box})


def search_form(request):
    form = ArendatorForm
    return render_to_response('catalog/search_form.html', {'form': form})


def search(request):
    form = ArendatorForm(request.GET)
    person = form.data['person']
    gos_num = form.data['gos_num']
    box_num = form.data['box_num']
    auto = form.data['auto']
    registered = form.data['registered']
    ended = form.data['ended']

    boxes = Arendator.objects.filter(person__icontains=person, gos_num__icontains=gos_num,
                                     box_num__icontains=box_num, auto__icontains=auto,
                                     registered__icontains=registered, ended__icontains=ended)
    return render_to_response('catalog/box_list.html', {'boxes': boxes})

catalog/templates/catalog/box_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список арендаторов</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
</head>
<body>
    <div><h1>Арендаторы</h1></div>

    <a href="{% url 'search_form' %}">Перейти к поиску по арендаторам</a>

    {% for box in boxes %}
    <div class="container">
        <h3>Номер бокса: {{ box.box_num }} </h3>
        <p>ФИО арендатора: {{ box.person }} </p>
        <p>Срок аренды: {{ box.registered}} - {{ box.ended}} </p>
        <p>Марка машины: {{ box.get_auto_display }}, гос. номер: {{ box.gos_num }}</p>
        <p>{% now "Y-m-d" as todays_date %}</p>

        {% if box.registered|date:"Y-m-d" <= todays_date and todays_date <= box.ended|date:"Y-m-d" %}

        {% if box.has_pass == True %}
        <p>Есть пропуск. Сдать? <a href="{% url 'return_pass' pk=box.pk %}">Сдать</a></p>
        {% else %}
        <p>Пропуска нет. Получить? <a href="{% url 'get_pass' pk=box.pk %}">Получить</a></p>
        {% endif %}

        {% else %}
        <p class="text-error">К сожалению, аренда данного бокса истекла.</p>

        {% endif %}

    </div>
    {% endfor %}

</body>
</html>

catalog/templates/catalog/get_pass.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Получить пропуск</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
</head>
<body>
<h3>Номер бокса: {{ box.box_num }} </h3>
<p>Арендатор {{box.person}} получил пропуск</p>
<a href="{% url 'box_list' %}">Вернуться к списку</a>
</body>
</html>

catalog/templates/catalog/return_pass.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сдать пропуск</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
</head>
<body>
<h3>Номер бокса: {{ box.box_num }} </h3>
<p>Арендатор {{box.person}} сдал пропуск</p>
<a href="{% url 'box_list' %}">Вернуться к списку</a>
</body>
</html>

catalog/templates/catalog/search_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поиск</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
</head>
<body>
    <div class="container">

        <h1> Поиск арендаторов </h1>
        <form id="searchform" action="{% url 'search' %}" method="get">
        {{form.as_p}}
        <button type="submit" class="btn">Поиск</button>
        </form>
    </div>

</body>
</html>